### ISSUE TITLE
Docker issues 0.2.1

### ISSUE THREAD

**Issue by creat89** [collab-uniba/Emotion_and_Polarity_SO#19]
Hello,

I'm trying to train a model with EmoTxt tool but it is not finding some files.

In the case I'm cloning the repository (the latest version of 14th feb 2019) I'm getting the same error indicated in issue #13.

In the case that I'm using the docker file version 0.2.1, I'm having two errors. The first one happens if I follow the command line `emtk emotions train -i ./emotions/LOVE.csv -d sc -e love`. In which the line 111 from the train.sh file is not finding the LOVE.csv as can be seen here:

```
train.sh: 29: [: unexpected operator
[ERROR]: The folder n-grams doesn't exists. I will extract the n-grams..
train.sh: 111: train.sh: cannot create training_LOVE_love/features-ids.csv: Directory nonexistent
awk: cannot open ./emotions/LOVE.csv (No such file or directory)
creating directory: training_LOVE_love
DIR created
creating directory: training_LOVE_love/ElaboratedFiles
DIR created
java.io.FileNotFoundException: ./emotions/LOVE.csv (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:21)
        at main.Main.main(Main.java:131)
Exception in thread "main" java.lang.NullPointerException
        at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:52)
        at main.Main.main(Main.java:131)
```

If we use instead the command: `sh train.sh -i ./LOVE.csv -d sc -e love`, everything runs fine until we arrive to the R part, 

```
CSV file training_LOVE_love/features-wordnet.csv was created successfully.
Time: 105 sec
paste: training_LOVE_love/features-ids.csv: No such file or directory
Loading required package: lattice
Loading required package: ggplot2
Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  no lines available in input
Calls: read.csv -> read.table
Error: object 'SO' not found
Error: object 'SO' not found
Error: object 'SO' not found
Error in na.omit(SO) : object 'SO' not found
Error: object 'SO' not found
Error in factor(SO[, outcomeName]) : object 'SO' not found
Error in createDataPartition(SO[, outcomeName], p = 0.7, list = FALSE) :
  object 'SO' not found
Error: object 'x' not found
Error: object 'x' not found
Error: object 'y' not found
Error: object 'y' not found
Error: object 'temp' not found
Error: object 'temp' not found
Error: object 'training' not found
Error: object 'testing' not found
[1] "Building model for classifier L2-regularized logistic regression (primal)"
[1] 0
Error in inherits(data, "matrix.csr") : object 'xTrain' not found
Calls: LiblineaR -> inherits
Loading required package: lattice
Loading required package: ggplot2
Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  no lines available in input
Calls: read.csv -> read.table
Error: object 'SO' not found
Error in na.omit(SO) : object 'SO' not found
Error: object 'SO' not found
Error in factor(SO[, outcomeName]) : object 'SO' not found
Error in downSample(x, y, list = FALSE, yname = outcomeName) :
  object 'x' not found
Error: object 'SO' not found
Error: object 'SO' not found
Error: object 'SO' not found
Error: object 'SO' not found
Error in factor(SO[, outcomeName]) : object 'SO' not found
Error in createDataPartition(SO[, outcomeName], p = 0.7, list = FALSE) :
  object 'SO' not found
Error: object 'x' not found
Error: object 'x' not found
Error: object 'y' not found
Error: object 'y' not found
Error: object 'temp' not found
Error: object 'temp' not found
Error: object 'temp' not found
Error: object 'training' not found
Error: object 'testing' not found
[1] "Building model for classifier L2-regularized logistic regression (primal)"
[1] 0
Error in inherits(data, "matrix.csr") : object 'xTrain' not found
Calls: LiblineaR -> inherits
```

Checking the files generated in liblinear, we get an empty trainingSet.csv and a testingSet.csv that only contain the head id, label. The Elaborated files seem fine, features-love.csv is empty, features-wordnet.csv seems fine, idfs files are ok .

**Comment by bateman** [comment]
Sorry for the late reply, can you try again with the latest image available from Docker.
Try and execute something like
`emtk emotions classify -i /emotions/LOVE_SMALL.csv -d sc -e love -p`

**Comment by creat89** [comment]
It's ok, I solve it by myself.
