### ISSUE TITLE
Error in library(caret)

### ISSUE THREAD

**Issue by akash9182** [collab-uniba/Emotion_and_Polarity_SO#6]
I get the following error

`creating directory: classification_file_fear
DIR created
creating directory: classification_file_fear/ElaboratedFiles
DIR created
Exception in thread "main" java.lang.IllegalArgumentException: Index for header 'text' is 2 but CSVRecord only has 1 values!
	at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:110)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:29)
	at main.Main.main(Main.java:129)
cp: cannot stat 'classification_file_fear/ElaboratedFiles/docs.py': No such file or directory
cp: cannot stat 'classification_file_fear/ElaboratedFiles/docs.py': No such file or directory
Exception in thread "main" java.lang.IllegalArgumentException: Index for header 'text' is 2 but CSVRecord only has 1 values!
	at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:110)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:29)
	at main.Main.main(Main.java:129)
Exception in thread "main" java.lang.IllegalArgumentException: Index for header 'text' is 2 but CSVRecord only has 1 values!
	at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:110)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:29)
	at main.Main.main(Main.java:129)
Exception in thread "main" java.lang.IllegalArgumentException: Index for header 'text' is 2 but CSVRecord only has 1 values!
	at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:110)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:29)
	at main.Main.main(Main.java:129)
Exception in thread "main" java.lang.IllegalArgumentException: Index for header 'text' is 2 but CSVRecord only has 1 values!
	at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:110)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:29)
	at main.Main.main(Main.java:129)
Exception in thread "main" java.lang.IllegalArgumentException: Index for header 'text' is 2 but CSVRecord only has 1 values!
	at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:110)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:29)
	at main.Main.main(Main.java:129)
Exception in thread "main" java.lang.IllegalArgumentException: Index for header 'text' is 2 but CSVRecord only has 1 values!
	at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:110)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:29)
	at main.Main.main(Main.java:129)
paste: classification_file_fear/features-SenPolImpolMoodModality.csv: No such file or directory
Error in library(caret) : there is no package called ‘caret’
Execution halted
`

I get this error when I run the following command 

`sh classify.sh -i file.csv -d sc -e fear
`
Any help would be appreciated

**Comment by bateman** [comment]
`there is no package called ‘caret’ `
your R installation is missing the caret package
make sure to follow installation instruction. you must have skipped executing `Rscript requirements.R` from the command line
