### ISSUE TITLE
Problems with installation and the example

### ISSUE THREAD

**Issue by Sedce** [collab-uniba/Emotion_and_Polarity_SO#9]
(base) bash-3.2$ sh classify.sh -i file.csv -d c -e joy
creating directory: classification_file_joy
DIR created
creating directory: classification_file_joy/ElaboratedFiles
DIR created
java.io.FileNotFoundException: file.csv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:21)
	at main.Main.main(Main.java:129)
Exception in thread "main" java.lang.NullPointerException
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:52)
	at main.Main.main(Main.java:129)
cp: classification_file_joy/ElaboratedFiles/docs.py: No such file or directory
cp: classification_file_joy/ElaboratedFiles/docs.py: No such file or directory
Traceback (most recent call last):
  File "model.py", line 5, in <module>
    import cPickle
ModuleNotFoundError: No module named 'cPickle'
cp: python/CalculatePoliteAndImpolite/textsPoliteAndImpolite.csv: No such file or directory
rm: python/CalculatePoliteAndImpolite/textsPoliteAndImpolite.csv: No such file or directory
Traceback (most recent call last):
  File "moodAndModality.py", line 2, in <module>
    from pattern.en import parse, Sentence, parse
ModuleNotFoundError: No module named 'pattern'
cp: python/CalculateMoodModality/textsMoodAndModality.csv: No such file or directory
rm: python/CalculateMoodModality/textsMoodAndModality.csv: No such file or directory
java.io.FileNotFoundException: file.csv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:21)
	at main.Main.main(Main.java:129)
Exception in thread "main" java.lang.NullPointerException
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:52)
	at main.Main.main(Main.java:129)
java.io.FileNotFoundException: file.csv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:21)
	at main.Main.main(Main.java:129)
Exception in thread "main" java.lang.NullPointerException
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:52)
	at main.Main.main(Main.java:129)
java.io.FileNotFoundException: file.csv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:21)
	at main.Main.main(Main.java:129)
Exception in thread "main" java.lang.NullPointerException
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:52)
	at main.Main.main(Main.java:129)
java.io.FileNotFoundException: file.csv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:21)
	at main.Main.main(Main.java:129)
Exception in thread "main" java.lang.NullPointerException
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:52)
	at main.Main.main(Main.java:129)
java.io.FileNotFoundException: file.csv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:21)
	at main.Main.main(Main.java:129)
Exception in thread "main" java.lang.NullPointerException
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:52)
	at main.Main.main(Main.java:129)
java.io.FileNotFoundException: file.csv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:21)
	at main.Main.main(Main.java:129)
Exception in thread "main" java.lang.NullPointerException
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:52)
	at main.Main.main(Main.java:129)
paste: classification_file_joy/features-SenPolImpolMoodModality.csv: No such file or directory
classify.sh: line 176: Rscript: command not found
mv: rename r/Liblinear/output/Results_joy/* to classification_file_joy/*: No such file or directory
rm: r/Liblinear/output/Results_joy: No such file or directory
rm: classification_file_joy/features-bigrams_1.csv: No such file or directory
rm: classification_file_joy/features-bigrams_2.csv: No such file or directory
rm: classification_file_joy/features-SenPolImpolMoodModality.csv: No such file or directory
rm: classification_file_joy/features-unigrams_1.csv: No such file or directory
rm: classification_file_joy/features-unigrams_2.csv: No such file or directory
rm: classification_file_joy/features-wordnet.csv: No such file or directory
(base) bash-3.2$ sh classify.sh -i sample.csv -d sc -e anger
creating directory: classification_sample_anger
DIR created
creating directory: classification_sample_anger/ElaboratedFiles
DIR created
Tokenizing input corpus ...
Loading depparse model file: edu/stanford/nlp/models/parser/nndep/english_UD.gz ... 
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Unable to open "edu/stanford/nlp/models/parser/nndep/english_UD.gz" as class path, filename or URL
	at edu.stanford.nlp.parser.nndep.DependencyParser.loadModelFile(DependencyParser.java:586)
	at edu.stanford.nlp.parser.nndep.DependencyParser.loadFromModelFile(DependencyParser.java:485)
	at edu.stanford.nlp.parser.nndep.DependencyParser.loadFromModelFile(DependencyParser.java:472)
	at analysis.Politeness.<init>(Politeness.java:21)
	at main.Main.main(Main.java:326)
Caused by: java.io.IOException: Unable to open "edu/stanford/nlp/models/parser/nndep/english_UD.gz" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:485)
	at edu.stanford.nlp.io.IOUtils.readerFromString(IOUtils.java:622)
	at edu.stanford.nlp.parser.nndep.DependencyParser.loadModelFile(DependencyParser.java:503)
	... 4 more
cp: classification_sample_anger/ElaboratedFiles/docs.py: No such file or directory
cp: classification_sample_anger/ElaboratedFiles/docs.py: No such file or directory
Traceback (most recent call last):
  File "model.py", line 5, in <module>
    import cPickle
ModuleNotFoundError: No module named 'cPickle'
cp: python/CalculatePoliteAndImpolite/textsPoliteAndImpolite.csv: No such file or directory
rm: python/CalculatePoliteAndImpolite/textsPoliteAndImpolite.csv: No such file or directory
Traceback (most recent call last):
  File "moodAndModality.py", line 2, in <module>
    from pattern.en import parse, Sentence, parse
ModuleNotFoundError: No module named 'pattern'
cp: python/CalculateMoodModality/textsMoodAndModality.csv: No such file or directory
rm: python/CalculateMoodModality/textsMoodAndModality.csv: No such file or directory
Tokenizing input corpus ...
Computing positive score..
Computing negative score...
Reading politeness and impoliteness..
java.io.FileNotFoundException: classification_sample_anger/ElaboratedFiles/textsPoliteAndImpolite.csv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:21)
	at main.Main.main(Main.java:232)
Exception in thread "main" java.lang.NullPointerException
	at reading.ReadingCSV.read_Column_CSV(ReadingCSV.java:52)
	at main.Main.main(Main.java:232)
Tokenizing input corpus ...
Loading unigrams..
Computing tf_idf for the doc 22

Computing tf_idf for the doc 23

Writing doc :22
Writing doc :23
Printing line:0
CSV file classification_sample_anger/features-unigrams_1.csv was created successfully.
Tokenizing input corpus ...
Loading bigrams..
Computing tf_idf for the doc 22

Computing tf_idf for the doc 23

Writing doc :22
Writing doc :23
Printing line:0
CSV file classification_sample_anger/features-bigrams_1.csv was created successfully.
Tokenizing input corpus ...
Loading unigrams..
Computing tf_idf for the doc 22

Computing tf_idf for the doc 23

Writing doc :22
Writing doc :23
Printing line:0
CSV file classification_sample_anger/features-unigrams_2.csv was created successfully.
Tokenizing input corpus ...
Loading bigrams..
Computing tf_idf for the doc 22

Computing tf_idf for the doc 23

Writing doc :22
Writing doc :23
Printing line:0
CSV file classification_sample_anger/features-bigrams_2.csv was created successfully.
Tokenizing input corpus ...
Computing tf_idf for the doc 22

Computing tf_idf for the doc 23

Computing tf_idf for the doc 22

Computing tf_idf for the doc 23

Computing tf_idf for the doc 22

Computing tf_idf for the doc 23

Computing tf_idf for the doc 22

Computing tf_idf for the doc 23

Writing doc :22
Writing doc :23
Printing line:0
CSV file classification_sample_anger/features-wordnet.csv was created successfully.
paste: classification_sample_anger/features-SenPolImpolMoodModality.csv: No such file or directory
classify.sh: line 176: Rscript: command not found
mv: rename r/Liblinear/output/Results_anger/* to classification_sample_anger/*: No such file or directory
rm: r/Liblinear/output/Results_anger: No such file or directory
rm: classification_sample_anger/features-SenPolImpolMoodModality.csv: No such file or directory
(base) bash-3.2$ 

I really don't know the problem, it creates the classification_sample_anger but it's empty.

**Comment by bateman** [comment]
there seems to be no file named file.csv in your path.
double check your file name


*Fabio Calefato*
*Assistant Professor, PhD | University of Bari, Italy*

site: http://collab.di.uniba.it/fabio
email: fabio.calefato@uniba.it
phone: +39 080 544 3261
<fabio.calefato@uniba.it>. <https://twitter.com/fcalefato>.

**Comment by Sedce** [comment]
Thank you so much!
